### ISSUE TITLE
Tracing HTTP data

### ISSUE THREAD

**Issue by h2non** [vinxi/trace#2]
- [x] URL
- [x] HTTP verb
- [x] Headers
- [x] Body (optional, enabled based on custom filters)
- [x] Remote IP

**Comment by h2non** [comment]
We're basically trying to trace all the HTTP traffic handled by the proxy. @groyoh Do you agree about this?

Bodies should be only processed if the developer explicitly wants it. Also, it should be easily enable/disable based on filters / rules, in order to determine when should perform the action (e.g: body is small, content-type is JSON...)

**Comment by groyoh** [comment]
Sounds good to me! Should we trace IP?

**Comment by h2non** [comment]
Sure. Remote IP address is a premise.

**Comment by h2non** [comment]
I believe we have everything we need for now. Closing.
